//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34209
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
    public enum GameDifficulty
    {
        EASY,
        MEDIUM,
        HARD
    }
    ;

    public enum GameMode
    {
        FIXED,
        EMOTIONAL
    }
    ;

    public class GameSettings
    {
        public GameMode gameMode;
        public GameDifficulty gameDifficulty;
    }
}

