//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34209
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;

namespace AssemblyCSharp
{
		public class ScoreController: MonoBehaviour
		{
				public PlayerController player;
				public Text scoreTextField;

				public void Start ()
				{
						
						//updateInfo ();
				}

				private int numCollisions = 0;

				public void collisionDetected (Collision collision)
				{
						numCollisions++;
						
						//updateInfo ();
				}

				private void updateInfo ()
				{
						scoreTextField.text = "Collisions: " + numCollisions + "\nBoost: " + (player.zSpeed-1).ToString("0.00");
				}

				public void Update ()
				{
						updateInfo ();
				}
		}
}

